// fetch api
// the promise is only ever rejected when we get a network error
fetch('endpoint.json').then((response) => {
    console.log('resolved', response);
    return response.json();
}).then(data => {
    console.log(data);
}).catch((err) => {
    console.log('rejected', err);
});